---
title: "SVM"
output: html_document
---
dataset 2 - SVM analysis

```{r}
P1s1 <- read.csv('/home/avnish/R/my_data/Dataset2/Exp 1 Data - 20 Subjects/P_6_s4data.csv', header=TRUE)#stringsAsFactors = FALSE
P1s1<- data.frame(P1s1, check.rows=TRUE)

#p1s1<-P1s1[,c(3, 5:9, 13:15, 26:28, 29:40, 46, 48, 57, 59, 68, 70)] #removed ID column for svm to work later on
p1s1<-P1s1[,c(9,26:27,30:40, 46, 48, 57, 59, 68, 70)]
p1s1[p1s1 ==""]<- NA
p1s1<-p1s1[,colSums(is.na(p1s1))<nrow(p1s1)] #remove column with all NA
p1s1<-p1s1[complete.cases(p1s1),] #remove rows with NA; Not yet...try to ignore na in the algo step


## split data into a train and test set
index <- 1:nrow(p1s1)
testindex <- sample(index, trunc(length(index)/3))#randomly choose one-third p1s1 rows to be in the test-set
testset <- p1s1[testindex,]
trainset <- p1s1[-testindex,]

# trainset$Action<-as.numeric(as.character(trainset$Action))
# trainset$missionTime<-as.character(trainset$missionTime)
# trainset$segment<-as.character(trainset$segment)
# trainset$Closest_Screen<-as.character(trainset$Closest_Screen)
# trainset$Closest_Control<-as.character(trainset$Closest_Control)

# trainset$Session<-as.numeric(trainset$Session)
# trainset$longTime<-as.numeric(trainset$longTime)
# trainset$Block<-as.numeric(trainset$Block)
# trainset$ScoreChange<-as.numeric(trainset$ScoreChange)
# trainset$score<-as.numeric(trainset$score)

## svm
library('e1071')
svm.model <- svm(Difficulty ~., data=trainset, cost=10, gamma=.1, na.action=na.omit)
svm.pred <- predict(svm.model, testset[,-1], na.action=na.omit)# -6

## rpart
library('rpart')
rpart.model <- rpart(Difficulty ~., data=trainset)
rpart.pred <- predict(rpart.model, testset[,-1], type = "class")

## compute SVM confusion matrix
a.svm<-table(pred = svm.pred, true = testset[,1])
a.svm
CCR.svm<-(a.svm[1,1]+a.svm[2,2]+a.svm[3,3])/(a.svm[1,1]+a.svm[1,2]+a.svm[1,3]+a.svm[2,1]+a.svm[2,2]+a.svm[2,3]+a.svm[3,1]+a.svm[3,2]+a.svm[3,3])
CCR.svm
## compute rpart confusion matrix
a.rpart<-table(pred = rpart.pred, true = testset[,1])
a.rpart
CCR.rpart<-(a.rpart[1,1]+a.rpart[2,2]+a.rpart[3,3])/(a.rpart[1,1]+a.rpart[1,2]+a.rpart[1,3]+a.rpart[2,1]+a.rpart[2,2]+a.rpart[2,3]+a.rpart[3,1]+a.rpart[3,2]+a.rpart[3,3])
CCR.rpart


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## error: "contrasts can be applied only to factors with 2 or more levels". Correction: remove the column which has only 1 level of factors
l<-sapply(trainset, function(x)is.factor(x))
l
m<-trainset[,names(which(l==TRUE))]
ifelse(n<-sapply(m,function(x)length(levels(x)))==1,"DROP","NODROP")

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




data(iris)
model <- svm(iris$Species~., iris)
res <- predict(model, newdata=iris)


```

You can also embed plots, for example:
```{r, echo=FALSE}
plot(cars)
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
